[[redirects]]
    from = "/story"
    to = "/#/story"
    status = 200

[[redirects]]
    from = "/case-study"
    to = "/#/case-study"
    status = 200

[[redirects]]
    from = "/about"
    to = "/#/about"
    status = 200

[[redirects]]
    from = "/playground"
    to = "/#/playground"
    status = 200